rvm:
  - 2.2.7
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_4.2.gemfile

sudo: false

language: ruby
cache: bundler

addons:
  postgresql: "9.4"
  apt:
    packages: postgresql-plpython-9.4

before_script:
  - psql -c "CREATE DATABASE chronomodel;" -U postgres

script:
  - bundle exec rake TEST_CONFIG=./spec/config.travis.yml

