rvm:
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1

sudo: false

language: ruby
cache: bundler

addons:
  postgresql: "9.4"
  apt:
    packages: postgresql-plpython-9.4
  code_climate:
    repo_token: dedfb7472ee410eec459bff3681d9a8fd8dd237e9bd7e8675a7c8eb7e253bba9


before_script:
  - psql -c "CREATE DATABASE chronomodel;" -U postgres

script:
  - bundle exec rake TEST_CONFIG=./spec/config.travis.yml

after_success:
  - bundle exec codeclimate-test-reporter
