rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.3.1

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5.0.gemfile

sudo: false

language: ruby
cache: bundler

addons:
  postgresql: "9.4"
  apt:
    packages: postgresql-plpython-9.4

before_script:
  - psql -c "CREATE DATABASE chronomodel;" -U postgres

script:
  - bundle exec rake TEST_CONFIG=./spec/config.travis.yml CODECLIMATE_REPO_TOKEN=dedfb7472ee410eec459bff3681d9a8fd8dd237e9bd7e8675a7c8eb7e253bba9
