rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3

addons:
  postgresql: "9.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-plpython-9.4
  - sudo service postgresql restart

bundler_args: --without development

before_script:
  - psql -c "CREATE DATABASE chronomodel;" -U postgres

script:
  - bundle exec rake TEST_CONFIG=./spec/config.travis.yml CODECLIMATE_REPO_TOKEN=dedfb7472ee410eec459bff3681d9a8fd8dd237e9bd7e8675a7c8eb7e253bba9
